# Generated by Django 3.1.5 on 2021-04-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_image',
        ),
    ]
