# Generated by Django 3.1.5 on 2021-04-24 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_author_auth_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='author/', verbose_name='Author Profile Image'),
            preserve_default=False,
        ),
    ]
