# Generated by Django 3.1.5 on 2021-04-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='catagories',
            field=models.ManyToManyField(null=True, to='blog.Catagory'),
        ),
    ]
