# Generated by Django 3.1.5 on 2021-04-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='show_hide',
            field=models.CharField(choices=[('show', 'show'), ('hide', 'hide')], default='show', max_length=5),
        ),
    ]
