# Generated by Django 3.1.5 on 2021-04-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_show_hide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='show_hide',
        ),
    ]
