# Generated by Django 3.1.5 on 2021-05-01 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_show_hide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='catagories',
        ),
        migrations.AddField(
            model_name='blog',
            name='catagories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.catagory'),
        ),
    ]
