# Generated by Django 3.1.5 on 2021-04-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210417_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='catagories',
            field=models.ManyToManyField(to='blog.Catagory'),
        ),
    ]
