# Generated by Django 3.1.5 on 2021-04-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210418_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
