# Generated by Django 3.1.5 on 2021-05-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210501_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='catagories',
        ),
        migrations.AddField(
            model_name='blog',
            name='catagories',
            field=models.ManyToManyField(null=True, to='blog.Catagory'),
        ),
    ]
