# Generated by Django 3.1.5 on 2021-05-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210502_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='visible',
            field=models.CharField(choices=[('show', 'show'), ('hide', 'hide')], default='show', max_length=10),
        ),
    ]
