# Generated by Django 3.1.5 on 2021-05-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210509_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('messages', models.TextField()),
                ('subject', models.CharField(max_length=200, null=True, verbose_name='Subjects')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
    ]
