# Generated by Django 3.1.5 on 2021-05-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210511_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
